import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "@/integrations/supabase/types";

// Hand-written sibling to src/integrations/supabase/auth-middleware.ts, which
// is regenerated by tooling and should not be hand-edited. Same technique
// (build a request-scoped Supabase client from the caller's bearer token),
// but this version NEVER rejects a request that has no token — it degrades
// to a plain anon-key client instead. That's the one behavioral difference
// from requireSupabaseAuth, and it's the whole point: guest checkout must
// keep working exactly as before, while a logged-in customer's session (if
// present) gets forwarded so create_order()/get_order() can resolve
// auth.uid() correctly.

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );
    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }
    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function getEnv(): { url: string; key: string } {
  const url = process.env["SUPABASE_URL"];
  const key = process.env["SUPABASE_PUBLISHABLE_KEY"];
  if (!url || !key) {
    throw new Error(
      "Missing Supabase environment variable(s): SUPABASE_URL / SUPABASE_PUBLISHABLE_KEY.",
    );
  }
  return { url, key };
}

function buildAnonClient(url: string, key: string) {
  return createClient<Database>(url, key, {
    global: { fetch: createSupabaseFetch(key) },
    auth: { persistSession: false, autoRefreshToken: false },
  });
}

function buildAuthedClient(url: string, key: string, token: string) {
  return createClient<Database>(url, key, {
    global: {
      fetch: createSupabaseFetch(key),
      headers: { Authorization: `Bearer ${token}` },
    },
    auth: { storage: undefined, persistSession: false, autoRefreshToken: false },
  });
}

/**
 * context.supabase — authenticated as the caller if they have a valid
 * session, otherwise a plain anon-key client (identical to what
 * orders.server.ts used before this middleware existed).
 * context.userId — the caller's auth.uid(), or null for a guest.
 */
export const attachOptionalSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const { url, key } = getEnv();
    const request = getRequest();
    const authHeader = request?.headers?.get("authorization");
    const token =
      authHeader && authHeader.startsWith("Bearer ") ? authHeader.slice("Bearer ".length) : null;

    let supabaseClient = buildAnonClient(url, key);
    let userId: string | null = null;

    if (token && token.split(".").length === 3) {
      const authedClient = buildAuthedClient(url, key, token);
      const { data, error } = await authedClient.auth.getClaims(token);

      // A valid token authenticates the client; an expired/malformed one
      // degrades to the anon client already set above rather than failing
      // the checkout outright — a stale token should never block an order.
      if (!error && data?.claims?.sub) {
        supabaseClient = authedClient;
        userId = data.claims.sub as string;
      }
    }

    return next({ context: { supabase: supabaseClient, userId } });
  },
);
