/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as OrderConfirmationRouteImport } from './routes/order-confirmation'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountForgotPasswordRouteImport } from './routes/account/forgot-password'
import { Route as AccountLoginRouteImport } from './routes/account/login'
import { Route as AccountResetPasswordRouteImport } from './routes/account/reset-password'
import { Route as AccountSignupRouteImport } from './routes/account/signup'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as StaffOrderNumberRouteImport } from './routes/staff/$orderNumber'
import { Route as StaffLoginRouteImport } from './routes/staff/login'
import { Route as StaffMenuRouteImport } from './routes/staff/menu'
import { Route as StaffSettingsRouteImport } from './routes/staff/settings'
import { Route as AccountOrdersIndexRouteImport } from './routes/account/orders/index'
import { Route as AccountOrdersOrderNumberRouteImport } from './routes/account/orders/$orderNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationRoute = OrderConfirmationRouteImport.update({
  id: '/order-confirmation',
  path: '/order-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountForgotPasswordRoute = AccountForgotPasswordRouteImport.update({
  id: '/account/forgot-password',
  path: '/account/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/account/login',
  path: '/account/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountResetPasswordRoute = AccountResetPasswordRouteImport.update({
  id: '/account/reset-password',
  path: '/account/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSignupRoute = AccountSignupRouteImport.update({
  id: '/account/signup',
  path: '/account/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffOrderNumberRoute = StaffOrderNumberRouteImport.update({
  id: '/staff/$orderNumber',
  path: '/staff/$orderNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff/login',
  path: '/staff/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffMenuRoute = StaffMenuRouteImport.update({
  id: '/staff/menu',
  path: '/staff/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffSettingsRoute = StaffSettingsRouteImport.update({
  id: '/staff/settings',
  path: '/staff/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersIndexRoute = AccountOrdersIndexRouteImport.update({
  id: '/account/orders/',
  path: '/account/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersOrderNumberRoute =
  AccountOrdersOrderNumberRouteImport.update({
    id: '/account/orders/$orderNumber',
    path: '/account/orders/$orderNumber',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/menu': typeof MenuRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/signup': typeof AccountSignupRoute
  '/staff/$orderNumber': typeof StaffOrderNumberRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/menu': typeof StaffMenuRoute
  '/staff/settings': typeof StaffSettingsRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/account/orders/$orderNumber': typeof AccountOrdersOrderNumberRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/menu': typeof MenuRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/signup': typeof AccountSignupRoute
  '/staff/$orderNumber': typeof StaffOrderNumberRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/menu': typeof StaffMenuRoute
  '/staff/settings': typeof StaffSettingsRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/staff': typeof StaffIndexRoute
  '/account/orders/$orderNumber': typeof AccountOrdersOrderNumberRoute
  '/account/orders': typeof AccountOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/menu': typeof MenuRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/signup': typeof AccountSignupRoute
  '/staff/$orderNumber': typeof StaffOrderNumberRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/menu': typeof StaffMenuRoute
  '/staff/settings': typeof StaffSettingsRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/account/orders/$orderNumber': typeof AccountOrdersOrderNumberRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/menu'
    | '/order-confirmation'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/reset-password'
    | '/account/signup'
    | '/staff/$orderNumber'
    | '/staff/login'
    | '/staff/menu'
    | '/staff/settings'
    | '/account/'
    | '/admin/'
    | '/staff/'
    | '/account/orders/$orderNumber'
    | '/account/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/menu'
    | '/order-confirmation'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/reset-password'
    | '/account/signup'
    | '/staff/$orderNumber'
    | '/staff/login'
    | '/staff/menu'
    | '/staff/settings'
    | '/account'
    | '/admin'
    | '/staff'
    | '/account/orders/$orderNumber'
    | '/account/orders'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/menu'
    | '/order-confirmation'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/reset-password'
    | '/account/signup'
    | '/staff/$orderNumber'
    | '/staff/login'
    | '/staff/menu'
    | '/staff/settings'
    | '/account/'
    | '/admin/'
    | '/staff/'
    | '/account/orders/$orderNumber'
    | '/account/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  MenuRoute: typeof MenuRoute
  OrderConfirmationRoute: typeof OrderConfirmationRoute
  AccountForgotPasswordRoute: typeof AccountForgotPasswordRoute
  AccountLoginRoute: typeof AccountLoginRoute
  AccountResetPasswordRoute: typeof AccountResetPasswordRoute
  AccountSignupRoute: typeof AccountSignupRoute
  StaffOrderNumberRoute: typeof StaffOrderNumberRoute
  StaffLoginRoute: typeof StaffLoginRoute
  StaffMenuRoute: typeof StaffMenuRoute
  StaffSettingsRoute: typeof StaffSettingsRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
  AccountOrdersOrderNumberRoute: typeof AccountOrdersOrderNumberRoute
  AccountOrdersIndexRoute: typeof AccountOrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation': {
      id: '/order-confirmation'
      path: '/order-confirmation'
      fullPath: '/order-confirmation'
      preLoaderRoute: typeof OrderConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/forgot-password': {
      id: '/account/forgot-password'
      path: '/account/forgot-password'
      fullPath: '/account/forgot-password'
      preLoaderRoute: typeof AccountForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/login': {
      id: '/account/login'
      path: '/account/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/reset-password': {
      id: '/account/reset-password'
      path: '/account/reset-password'
      fullPath: '/account/reset-password'
      preLoaderRoute: typeof AccountResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/signup': {
      id: '/account/signup'
      path: '/account/signup'
      fullPath: '/account/signup'
      preLoaderRoute: typeof AccountSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/$orderNumber': {
      id: '/staff/$orderNumber'
      path: '/staff/$orderNumber'
      fullPath: '/staff/$orderNumber'
      preLoaderRoute: typeof StaffOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/login': {
      id: '/staff/login'
      path: '/staff/login'
      fullPath: '/staff/login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/menu': {
      id: '/staff/menu'
      path: '/staff/menu'
      fullPath: '/staff/menu'
      preLoaderRoute: typeof StaffMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/settings': {
      id: '/staff/settings'
      path: '/staff/settings'
      fullPath: '/staff/settings'
      preLoaderRoute: typeof StaffSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders/': {
      id: '/account/orders/'
      path: '/account/orders'
      fullPath: '/account/orders/'
      preLoaderRoute: typeof AccountOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders/$orderNumber': {
      id: '/account/orders/$orderNumber'
      path: '/account/orders/$orderNumber'
      fullPath: '/account/orders/$orderNumber'
      preLoaderRoute: typeof AccountOrdersOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  MenuRoute: MenuRoute,
  OrderConfirmationRoute: OrderConfirmationRoute,
  AccountForgotPasswordRoute: AccountForgotPasswordRoute,
  AccountLoginRoute: AccountLoginRoute,
  AccountResetPasswordRoute: AccountResetPasswordRoute,
  AccountSignupRoute: AccountSignupRoute,
  StaffOrderNumberRoute: StaffOrderNumberRoute,
  StaffLoginRoute: StaffLoginRoute,
  StaffMenuRoute: StaffMenuRoute,
  StaffSettingsRoute: StaffSettingsRoute,
  AccountIndexRoute: AccountIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
  AccountOrdersOrderNumberRoute: AccountOrdersOrderNumberRoute,
  AccountOrdersIndexRoute: AccountOrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
