// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abwpbtwkqkmjhvqhcghg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFid3BidHdrcWttamh2cWhjZ2hnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODgyOTcxMjAsImV4cCI6MjEwMzg3MzEyMH0.Y8kmvViB9jZ6Lb2XzYq3jxEjK5fbnOzDP09vlOrixKg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});